spring.application.name=controle_despesas

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA Settings // HIBERNATES
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
