CREATE TABLE tb_parcelamento
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_parcelamento SMALLINT,
    valor_original      DECIMAL,
    valor_parcela       DECIMAL,
    valor_parcelado     DECIMAL,
    quantidade_parcelas INTEGER,
    parcelas_pagas      INTEGER,
    data_inicio         date,
    tipo_juros          SMALLINT,
    taxa_juros          DECIMAL,
    CONSTRAINT pk_tb_parcelamento PRIMARY KEY (id)
);