CREATE TABLE IF NOT EXISTS tb_despesa
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao       VARCHAR(255),
    valor_original  DECIMAL,
    valor_total     DECIMAL,
    tipo            SMALLINT,
    prioridade      SMALLINT,
    status          SMALLINT,
    data_vencimento date,
    parcelamento_id BIGINT,
    CONSTRAINT pk_tb_despesa PRIMARY KEY (id)
);

ALTER TABLE tb_despesa
    ADD CONSTRAINT uc_tb_despesa_parcelamento UNIQUE (parcelamento_id);

ALTER TABLE tb_despesa
    ADD CONSTRAINT FK_TB_DESPESA_ON_PARCELAMENTO FOREIGN KEY (parcelamento_id) REFERENCES tb_parcelamento (id);